mainapp/urls.py
from django.urls import path

from . import views, reports

app_name="mainapp"

urlpatterns = [
    path('kutuphane/', views.index),
    path('kutuphane/index/',views.index,name='index'),
    path('kutuphane/searchbook/', views.searchbook, name='searchbook'),
    path('kutuphane/addbook/', views.addbook, name='addbook'),
    path('kutuphane/units/', views.units, name='units'),
    #path('libraries/', views.libraries, name='libraries'),
    path('kutuphane/addreader/<str:school_num>/<str:library_entry_id>', views.addreader, name='addreader'),
    path('kutuphane/save_lending/<str:school_num>/<str:library_entry_id>', views.save_lending, name='save_lending'),
    path('kutuphane/inventory/', views.inventory, name='inventory'),
    path('kutuphane/login/', views.login, name='login'),
    path('kutuphane/users/', views.users, name='users'),
    path("kutuphane/books/<str:isbn>", views.the_book, name="book"),
    path("kutuphane/lending/<str:library_entry_id>", views.lending, name="lending"),
    path("kutuphane/success/",views.success,name="success"),
    path("kutuphane/report/", reports.report,name="report"),
    path("kutuphane/admin_report/", reports.admimistrative_report,name="admin_report"),
    path("kutuphane/which_lib/<str:isbn>",views.which_lib, name="which_lib"),
    path("kutuphane/reader_detail/<str:id>",reports.reader_detail, name="reader_detail"),
    path("kutuphane/take_back",views.take_back,name="take_back"),

]

mainapp/models.py
from django.db import models
from django.db.models import UniqueConstraint, Q
from django.contrib.auth.models import User


class Unit(models.Model):
    id=models.CharField(max_length=8, primary_key=True)
    user=models.ForeignKey(User, on_delete=models.CASCADE)
    name=models.CharField(max_length=100)
    address=models.CharField(max_length=200)
    #user=models.OneToOneField(User, on_delete=models.CASCADE)
    def __str__(self):
        return self.name+" - "+self.address

class Book(models.Model):
    isbn=models.CharField(verbose_name="isbn",max_length=13, primary_key=True)
    title=models.CharField(verbose_name="kitap adı",max_length=50)
    writer=models.CharField(verbose_name="yazar",max_length=50 )
    genre=models.CharField(verbose_name="tür",max_length=20)
    publisher=models.CharField(verbose_name="yayıncı",max_length=20)
    publish_year=models.IntegerField(verbose_name="yayın yılı",)
    pages=models.IntegerField(blank=True, verbose_name="Sayfa Sayısı")
    def __str__(self):
        return self.isbn +"-"+self.title

class Library(models.Model):
    unit=models.ForeignKey(Unit, on_delete=models.CASCADE)
    book=models.ForeignKey(Book,on_delete=models.CASCADE)
    amount=models.IntegerField(default=1)
    on_lending=models.IntegerField(default=0)
    description=models.CharField(max_length=100, default="")

    def __str__(self):
        return self.unit.__str__() +" - "+self.book.__str__()


class Reader(models.Model):
    unit=models.ForeignKey(Unit, on_delete=models.CASCADE)
    school_num=models.CharField(max_length=10, verbose_name="Okul Numarası")
    id=models.CharField(max_length=20, primary_key=True)
    name=models.CharField(max_length=50, verbose_name="İsim")
    grade=models.IntegerField(verbose_name="Sınıf")
    department=models.CharField(max_length=5, verbose_name="Şube")
    books_lended=models.IntegerField(default=0)
    books_on=models.IntegerField(default=0)
    def __str__(self):
        return str(self.grade)+"/"+self.department+" - "+self.school_num +" "+self.name


class Lending(models.Model):
    unit=models.ForeignKey(Unit, on_delete=models.CASCADE)
    library_entry=models.ForeignKey(Library, on_delete=models.CASCADE)
    reader=models.ForeignKey(Reader, on_delete=models.CASCADE)
    lend_date=models.DateField()
    back_date=models.DateField()
    returned=models.BooleanField(default=False)

    def __str__(self):
        return self.reader.__str__() +"-"+self.library_entry.book.__str__()

mainapp/forms.py
from django.forms import ModelForm
from .models import Unit, Book, Library, Reader, Lending
from django.contrib.auth.models import User

class UnitForm(ModelForm):
    class Meta:
        model=Unit
        fields=['id','name','address']

class BookForm(ModelForm):
    class Meta:
        model=Book
        fields='__all__'

class LibraryForm(ModelForm):
    class Meta:
        model=Library
        fields=['book','amount']

class ReaderForm(ModelForm):
    class Meta:
        model=Reader
        fields=['name','grade','department']

class LendingForm(ModelForm):
    class Meta:
        model=Lending
        fields='__all__'

class UserForm(ModelForm):
        class Meta:
            model=User
            fields=['username', 'password']

mainapp/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect, HttpResponse
from .forms import UnitForm, BookForm, LibraryForm, ReaderForm, LendingForm, UserForm
from .models import Book, Unit, Library, Reader, Lending
from django.contrib.auth.decorators import login_required, user_passes_test
from django.shortcuts import redirect
from datetime import datetime, timedelta
from django.core.exceptions import ObjectDoesNotExist
import csv
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
from random import shuffle


@login_required
def register_book(request, book, unit, description=""):
    try:
        library_entry=Library.objects.filter(unit=unit).get(book=book)
        #kitap varsa sayısını bir artır
        library_entry.amount=library_entry.amount+1
    except Exception as e:
        #ancak kitap yoksa yeni bir kayıt oluştur
        library_entry=Library(unit=unit,book=book)

    library_entry.description=description
    library_entry.save()
    return library_entry

def index(request):
    msg=""
    units=Unit.objects.all()
    liste=None
    lib_set=None
    if request.method=="POST":
        search_type=request.POST.get("search_type")
        search_text=request.POST.get("search_text")
        which_unit=request.POST.get("which_unit")

        if which_unit=="all" and search_text!="":
            if search_type=="isbn":
                liste=Book.objects.filter(isbn__contains=search_text)
            elif search_type=="title":
                liste=Book.objects.filter(title__contains=search_text)
            elif search_type=="writer":
                liste=Book.objects.filter(writer__contains=search_text)
        elif which_unit=="all" and search_text=="":
            #msg="Ne arıyorsunuz?"
            liste=Book.objects.all()
        elif which_unit!="all" and search_text!="":
            the_library=Library.objects.filter(unit=Unit.objects.get(id=which_unit))
            book_list=None

            if search_type=="isbn":
                book_list=list(Book.objects.filter(isbn__contains=search_text))
            elif search_type=="title":
                book_list=list(Book.objects.filter(title__contains=search_text))
            elif search_type=="writer":
                book_list=list(Book.objects.filter(writer__contains=search_text))
            lib_set=the_library.filter(book__in = book_list)
        elif which_unit!="all" and search_text=="":
            the_library=Library.objects.filter(unit=Unit.objects.get(id=which_unit))
            #msg=str(which_unit)+" kütüphanesinde ne arıyorsunuz? "
            lib_set=the_library.all()
        else:
            liste=Book.objects.all()

    else:
        liste=Book.objects.all()

    '''
    liste=list(liste)
    shuffle(liste)
    '''
    if liste!=None:
        paginator=Paginator(liste,25)
        page=request.GET.get('page')
        liste=paginator.get_page(page)


    return render(request,'mainapp/index.html', {'liste':liste, 'msg':msg, 'units':units, 'lib_set':lib_set})

@login_required
def success(request):
    return render(request,"mainapp/success.html")


@login_required
def searchbook(request):
    msg=""
    if request.method=="POST":
        search=request.POST.get("search_text")
        #kitap kayıtlarda varsa;
        liste=Book.objects.filter(isbn=search)
        if not liste:
            return redirect("/kutuphane/addbook")
    else:
        liste=Book.objects.all()
    paginator=Paginator(liste,25)
    page=request.GET.get('page')
    liste=paginator.get_page(page)

    return render(request,'mainapp/searchbook.html',{'liste':liste, 'title':'Kitap Ara', 'msg':msg})

@login_required
def addbook(request):
    msg=""
    if request.method == 'POST':
        formset = BookForm(request.POST)
        if formset.is_valid():
            book=formset.save()
            description=request.POST.get("description")
            register_book(request, book,Unit.objects.get(id=request.user.username), description)
            return redirect("/kutuphane/success")

    else:
        msg="Aradığınız kitap bulunamadı, Eklemek için aşağıdaki formu doldurunuz."
        formset=BookForm()
    return render(request,'mainapp/addbook.html', {'formset':formset, 'msg':msg})


@login_required
def inventory(request):
    ##kitapları kütüphane girişlerinden süzüp getir
    liste=Library.objects.filter(unit=Unit.objects.get(id=request.user.username))

    if request.method=="POST":
        search_text=request.POST.get("search_text")
        try:
            liste=liste.filter(book=Book.objects.get(isbn=search_text))
        except Exception as e:
            ##lan oğlum böyle olmaz
            #liste boşsa boştur orjinali aramadan önceki halini gösteririz
            pass

    paginator=Paginator(liste,25)
    page=request.GET.get('page')
    liste=paginator.get_page(page)

    return render(request,'mainapp/inventory.html', {'liste':liste})


def which_lib(request, isbn):
    try:
        book=Book.objects.get(isbn=isbn)
    except ObjectDoesNotExist:
        return redirect("/kutuphane/index")
    liste=Library.objects.filter(book=book)
    units=[]
    for l in liste:
        units.append(l.unit)
    return render(request,'mainapp/which_lib.html', {'book':book, 'units':units})

@login_required
def save_lending(request,school_num,library_entry_id):
    unit_id=request.user.username
    reader_id=unit_id+'-'+school_num

    try:
        reader=Reader.objects.get(id=reader_id)
        library_entry=Library.objects.get(id=library_entry_id)
        if request.method=='POST':
            library_entry.on_lending+=1
            library_entry.save()
            reader.books_lended+=1
            reader.books_on+=1
            reader.save()
            l=Lending(unit=Unit.objects.get(id=request.user.username),
                                            reader=reader,
                                            library_entry=library_entry,
                                            lend_date=datetime.now().strftime("%Y-%m-%d"),
                                            back_date=(datetime.now() + timedelta(days=14)).strftime("%Y-%m-%d"))
            l.save()
            return redirect("/kutuphane/success")

    except ObjectDoesNotExist:
        url="/lending/"+library_entry_id
        return redirect(url)

    return render(request, 'mainapp/lending_summary.html',{'library_entry':library_entry,'reader':reader})


@login_required
def addreader(request, school_num, library_entry_id):
    msg="Kayıt Giriniz."
    formset=ReaderForm()
    unit_id=request.user.username
    reader_id=unit_id+'-'+school_num
    library_entry=Library.objects.get(id=library_entry_id)
    if request.method == 'POST':
        formset = ReaderForm(request.POST)
        if formset.is_valid():
            if Reader.objects.filter(id=reader_id).exists():
                msg="kullanıcı zaten kayıtlı"
                formset=ReaderForm()
            else:
                reader=formset.save(commit=False)
                reader.unit=Unit.objects.get(id=unit_id)
                reader.id=reader_id
                reader.school_num=school_num
                reader.save()
                url="/kutuphane/save_lending/"+school_num+"/"+library_entry_id
                return redirect(url)

    return render(request,'mainapp/adduser.html',{'library_entry':library_entry,
                                                    'formset':formset,
                                                    'title':'addreader',
                                                    'msg':msg})


@login_required
def lending(request,library_entry_id):
    library_entry=Library.objects.get(id=library_entry_id)

    if request.method == 'POST':
        school_num=request.POST.get("school_num")
        unit_id=request.user.username
        reader_id=unit_id+'-'+school_num
        try:
            reader=Reader.objects.get(id=reader_id)
            url="/kutuphane/save_lending/"+school_num+"/"+library_entry_id
            return redirect(url)
        except ObjectDoesNotExist:
            url="/kutuphane/addreader/"+school_num+"/"+library_entry_id
            return redirect(url)
    else:
        return render(request,'mainapp/lending.html', {'library_entry':library_entry})


@login_required
def take_back(request):
    msg=""
    unit_id=request.user.username
    lendings=Lending.objects.filter(unit=Unit.objects.get(id=unit_id)).filter(returned=False)
    ### TODO: kullanıcı araması için bir inputtan bilgi al
    ### kullanıcıyı bul, yoksa yaratılacak formu göster
    if request.method == 'POST':
        school_num=request.POST.get("school_num")
        if school_num:
            try:
                lendings=Lending.objects.filter(reader=Reader.objects.filter(unit_id=unit_id).get(school_num=school_num))
            except ObjectDoesNotExist:
                msg="Aradığınız kayıt bulunamadı..."
                pass
        lending_id=request.POST.get("lending_id")
        if lending_id:

            l=Lending.objects.get(id=lending_id)
            l.back_date=datetime.now().strftime("%Y-%m-%d")
            l.returned=True
            l.library_entry.on_lending-=1
            l.library_entry.save()
            l.reader.books_on-=1
            l.reader.save()
            l.save()

            msg="iade alındı..."
    return render(request,'mainapp/take_back.html', {'lendings':lendings, 'msg':msg})



def login(request):
    return render(request,'mainapp/login.html')

@user_passes_test(lambda user:user.is_staff )
def users(request):
    if request.method == 'POST':
        formset = UserForm(request.POST)
        if formset.is_valid():
            formset.save()
            formset=UserForm()
    else:
        formset=UserForm()
    return render(request,'mainapp/formset.html',{'formset':formset,'title':'users'})

@user_passes_test(lambda user:user.is_superuser)
def units(request):
    msg="Kayıt Giriniz."
    if request.method == 'POST':
        formset = UnitForm(request.POST)

mainapp/templates/mainapp/addbook.html
{% extends './base.html' %}

{% block content %}
<strong>{{msg}}</strong>
<br>
<form method="post">
  {% csrf_token %}
    <table>
  {{formset}}
  <tr>
    <td><strong>Açıklama : </strong></td>
    <td><input type="text" id="description" name="description"><br></td>
  </tr>
  </table>

  <input type="submit" value="Kaydet">

</form>


{% endblock %}

mainapp/templates/mainapp/adduser.html
{% extends './base.html' %}

{% block content %}
<strong>ISBN      :</strong> {{library_entry.book.isbn}}
<br>
<strong>Kitap Adı :</strong> {{library_entry.book.title}}
<br>
<strong>Yazar     :</strong> {{library_entry.book.writer}}
<br>

{{msg}}

<form method="post">
  {% csrf_token %}

  {{formset.as_p}}

  <input type="submit" value="Kaydet">

</form>


{% endblock %}

mainapp/templates/mainapp/admin_report.html
{% extends './base.html' %}

{% block content %}
<strong>Raporlar</strong>

<p> <strong>{{msg}}</strong></p>


<form method="post">
  {% csrf_token %}
  <select name="which_unit" id="which_unit">
    <option value="all">Tüm Kütüphaneler</option>
    {%for u in units%}
      <option value="{{u.id}}">{{u}}</option>
    {% endfor %}
    </select>


  <p>Lütfen rapor almak istediğiniz tabloyu seçiniz :</p>
  <input type="radio" id="book" name="selection" value="books">
  <label for="book">Kitaplar</label><br>
  <input type="radio" id="reader" name="selection" value="readers">
  <label for="reader">Okurlar</label><br>
  <input type="radio" id="lending" name="selection" value="lendings">
  <label for="lending">Ödünç verme</label>
  <br>
  <br>
  <input type="submit" value="Seç">

</form>
 <br>
 <table class="books-table">
  <tr>
    {%for h in header%}
    <th>
        {{h}}
    </th>
    {%endfor%}
  </tr>

  {% if selection == "readers"%}
    {%for item in liste%}
        <tr>
          <td>
            <a href="/kutuphane/reader_detail/{{item.id}}">
            {{item.school_num}}
            </a>
          </td>
          <td>
            {{item.name}}
          </td>
          <td>
            {{item.grade}}
          </td>
          <td>
            {{item.department}}
          </td>

            <td>
              <a href="/kutuphane/reader_detail/{{item.id}}">
                {{item.books_lended}}
              </a>
            </td>
        </tr>
      {%endfor%}
    {% else %}
     {%for item in liste%}
       <tr>
         {%for i in item%}
           <td>
             {{i}}
           </td>
         {%endfor%}
       </tr>
     {%endfor%}
    {% endif %}

  </table>




{% endblock %}

mainapp/templates/mainapp/base.html
{% load static %}
<!DOCTYPE html>
<html lang="tr" dir="ltr">
  <head>
    <meta charset="utf-8">
    <link rel="stylesheet" type="text/css", href="{% static 'css/main.css'%}">
    <title>Niğde İl Milli Eğitim Müdürlüğü - Kütüphane Otomasyonu</title>
    <link rel = "icon" href = "{% static 'images/icon.png'%}" type = "image/x-icon">
  </head>
  <body >
    <div class="content">

        <div class="header">

          <div class="header-child">
            <a href="http://www.meb.gov.tr/" target="_self" >
                <img class="logo" src="{% static 'images/logo.png'%}" alt="logo">
            </a>
          </div>

          <div class="header-child" >
            <img class="atam" src="{% static 'images/ataturk.png'%}" alt="Atam">
          </div>

        </div>

        <hr>
        <div class="greeting">
          {% if user.is_superuser %}
          <h3>Hoşgeldiniz, Yönetici!</h3>
          {% else %}
          {% if user.is_authenticated %}
          <h3>Hoşgeldiniz, {{ user.username|default:'Misafir' }} Kullanıcısı!</h3>
          {% else %}
          <h3>Hoşgeldiniz!</h3>
          {% endif %}
          {% endif %}
        </div>

        <nav>
          <a href="{% url 'mainapp:index' %}">Anasayfa</a>&nbsp;
          {% if user.is_superuser %}
                <a href="{% url 'mainapp:admin_report' %}">Raporlar</a>&nbsp;
          {% else %}
            {% if user.is_authenticated %}
                <a href="{% url 'mainapp:inventory' %}">Ödünç Verme</a>&nbsp;
                <a href="{% url 'mainapp:take_back' %}">İade İşlemleri</a>&nbsp;
                <a href="{% url 'mainapp:searchbook' %}">Kitap Ekleme</a>&nbsp;
                <a href="{% url 'mainapp:report' %}">Raporlar</a>&nbsp;
            {% endif %}
          {% endif %}

          {% if user.is_authenticated %}
              <a href="{% url 'logout' %}">Oturumu kapat</a>
          {% else %}
              <a href="{% url 'login' %}">Oturum aç</a>
          {% endif %}
        </nav>
        <hr>
      <br>


      {%block content%}
      {%endblock content%}

    <p class="geri">
        <a  href="#" onclick="history.go(-1)">Önceki Sayfa</a>
    </p>
      <hr>
      <footer>
        <p>
          &copy - 2022
        </p>


      </footer>
  </div>
  </body>
</html>

mainapp/templates/mainapp/book.html
{% extends './base.html' %}

{% block content %}
<form method="post">
  {% csrf_token %}

    <strong>ISBN      :</strong> {{book.isbn}}
    <br>
    <strong>Kitap Adı :</strong> {{book.title}}
    <br>
    <strong>Yazar     :</strong> {{book.writer}}
    <br>
    <strong>Açıklama  :</strong> <input type="text" id="description" name="description"><br>
    <br>
  <input type="submit" name="add" value="Ekle">
</form>


{% endblock %}

mainapp/templates/mainapp/error_404.html
{% extends './base.html' %}

{% block content %}
<strong>
<p>Sitemizin böyle bir hizmeti bulunmamaktadır...</p>
</strong>
{% endblock %}

mainapp/templates/mainapp/formset.html
{% extends './base.html' %}

{% block content %}
{{msg}}
<form method="post">
  {% csrf_token %}

  {{formset.as_p}}

  <input type="submit" value="Kaydet">

</form>


{% endblock %}

mainapp/templates/mainapp/inventory.html
{% extends './base.html' %}

{% block content %}
<strong>Ödünç Verme İşlemleri</strong>
<form method="post">
  {% csrf_token %}
  ISBN :
  <input type="text" name="search_text">
  <input type="submit" name="search" value="Ara">
</form>
<table class="books-table">
  <tr>
      <th>
          <h4>ISBN</h4>
      </th>
      <th>
          <h4>Kitap Adı</h4>
      </th>
      <th>
          <h4>Yazar</h4>
      </th>
      <th>
          <h4>Ödünçtekiler</h4>
      </th>
      <th>
          <h4>Toplam</h4>
      </th>
</tr>
{%for z in liste%}

  <tr>
  <td>
    {%if z.on_lending < z.amount %}
        <a href="/kutuphane/lending/{{z.id}}">{{z.book.isbn}}</a>
    {%else%}
        {{z.book.isbn}}
    {%endif%}
  </td>
  <td>
    {{z.book.title}}
  </td>
  <td>
    {{z.book.writer}}
  </td>
  <td>
    {{ z.on_lending }}
  </td>
  <td>
    {{ z.amount }}
  </td>
</tr>
{%endfor%}
</table>

<div class="page-selectors">
  {% if liste.has_previous %}
    <a href="?page={{ liste.previous_page_number}}">Önceki</a>
  {% endif %}
  {% if liste.has_next %}
    <a href="?page={{ liste.next_page_number}}">Sonraki</a>
  {% endif %}
</div>
{% endblock %}

mainapp/templates/mainapp/lending_summary.html
{% extends './base.html' %}

{% block content %}
{{msg}}
<form method="post">
  {% csrf_token %}

  <strong>ISBN      :</strong> {{library_entry.book.isbn}}
  <br>
  <strong>Kitap Adı :</strong> {{library_entry.book.title}}
  <br>
  <strong>Yazar     :</strong> {{library_entry.book.writer}}
  <br>


  {{reader}}
  <br>
  <input type="submit" name="save" value="Ödünç Ver">





</form>


{% endblock %}

mainapp/templates/mainapp/reader_detail.html
{% extends './base.html' %}

{% block content %}

<p><strong>{{reader.unit}} - {{reader}}</strong></p>

{% if liste %}
<p><strong>Okuduğu Kitaplar</strong></p>


<table class="books-table">
  <tr>
    {%for h in header%}
      <th>
          <h4>{{h}}</h4>
      </th>
    {%endfor%}
  </tr>


  {%for l in liste%}
    <tr>
      <td>
        <a href="/kutuphane/which_lib/{{l.library_entry__book__isbn}}">{{l.library_entry__book__isbn}}</a>
      </td>
      <td>
        {{l.library_entry__book__title}}
      </td>
      <td>
        {{l.lend_date}}
      </td>
      <td>
        {{l.back_date}}
      </td>
    </tr>
  {%endfor%}
{% endif %}
</table>
{% endblock %}

mainapp/templates/mainapp/report.html
{% extends './base.html' %}

{% block content %}
<strong>Raporlar</strong>

<p> <strong>{{msg}}</strong></p>


<form method="post">
  {% csrf_token %}
  <p>Lütfen rapor almak istediğiniz tabloyu seçiniz :</p>
  <input type="radio" id="book" name="selection" value="books">
  <label for="book">Kitaplar</label><br>
  <input type="radio" id="reader" name="selection" value="readers">
  <label for="reader">Okurlar</label><br>
  <input type="radio" id="lending" name="selection" value="lendings">
  <label for="lending">Ödünç verme</label>
  <br>
  <br>
  <input type="submit" value="Seç">

</form>
<br>


<table class="books-table">
 <tr>
   {%for h in header%}
   <th>
       {{h}}
   </th>
   {%endfor%}
 </tr>

 {% if selection == "readers"%}
   {%for item in liste%}
       <tr>
         <td>
           <a href="/kutuphane/reader_detail/{{item.id}}">
           {{item.school_num}}
           </a>
         </td>
         <td>
           {{item.name}}
         </td>
         <td>
           {{item.grade}}
         </td>
         <td>
           {{item.department}}
         </td>

           <td>
             <a href="/kutuphane/reader_detail/{{item.id}}">
               {{item.books_lended}}
             </a>
           </td>
       </tr>
     {%endfor%}
   {% else %}
    {%for item in liste%}
      <tr>
        {%for i in item%}
          <td>
            {{i}}
          </td>
        {%endfor%}
      </tr>
    {%endfor%}
   {% endif %}

 </table>



{% endblock %}

mainapp/templates/mainapp/searchbook.html
{% extends './base.html' %}

{% block content %}
<strong>Kitap Ekleme</strong><br>
Eklemek istediğiniz kitabı "isbn" ile aratınız<br>
{{msg}}
<form method="post">
  {% csrf_token %}
  ISBN :
  <input type="text" maxlength="13" name="search_text">
  <input type="submit" name="search" value="Ara">
</form>
<form method="post">
  <table class="books-table">
    <tr>
        <th>
            <h4>ISBN</h4>
        </th>
        <th>
            <h4>Kitap Adı</h4>
        </th>
        <th>
            <h4>Yazar</h4>
        </th>
        <th>
            <h4> </h4>
        </th>
  </tr>
  {%for l in liste%}

    <tr>
    <td>
      <a href="/kutuphane/books/{{l.isbn}}">{{l.isbn}}</a>
    </td>
    <td>
      {{l.title}}
    </td>
    <td>
      {{l.writer}}
    </td>
  </tr>
  {%endfor%}
  </table>
</form>
<div class="page-selectors">
  {% if liste.has_previous %}
    <a href="?page={{ liste.previous_page_number}}">Önceki</a>
  {% endif %}
  {% if liste.has_next %}
    <a href="?page={{ liste.next_page_number}}">Sonraki</a>
  {% endif %}
</div>
{% endblock %}

mainapp/templates/mainapp/take_back.html
{% extends './base.html' %}

{% block content %}
<strong>Kitap İade İşlemleri</strong>
<br>
<br>
<span style="color:red">{{msg}}</span>
<br>
<br>
<form method="post">
  {% csrf_token %}
  Okul Numarası :
  <input type="text" name="school_num">
  <input type="submit" name="search" value="Ara">
</form>
<form method="post">
  {% csrf_token %}

<table class="books-table">
  <tr>

      <th>
          <h4>Okul Numarası</h4>
      </th>
      <th>
          <h4>ISBN</h4>
      </th>
      <th>
          <h4>Kitap Adı</h4>
      </th>
      <th>
          <h4>Yazar</h4>
      </th>
      <th>
          <h4>Açıklama</h4>
      </th>
      <th>
          <h4>İade</h4>
      </th>


</tr>
{%for l in lendings%}

  <tr>
    <td>
      {{l.reader.school_num}}
    </td>
  <td>
        {{l.library_entry.book.isbn}}

  </td>
  <td>
    {{l.library_entry.book.title}}
  </td>
  <td>
    {{l.library_entry.book.writer}}
  </td>
  <td>
    {{l.library_entry.description}}
  </td>
  <td>
    <input type="hidden" id="lending_id" name="lending_id", value={{l.id}}>
    <input type="submit" name="take_it_back" value="İade Al">
  </td>
</tr>
{%endfor%}
</table>


</form>
{% endblock %}

mainapp/templates/mainapp/which_lib.html
{% extends './base.html' %}

{% block content %}
<strong>Bulunan Kütüphaneler</strong>
{{nsg}}
<form method="post">
  {% csrf_token %}
</form>
<table class="books-table">
  <tr>
      <th>
          <h4>ISBN</h4>
      </th>
      <th>
          <h4>Kitap Adı</h4>
      </th>
      <th>
          <h4>Yazar</h4>
      </th>
      <th>
          <h4>Tür</h4>
      </th>
      <th>
          <h4>Sayfa Sayısı</h4>
      </th>
      <th>
          <h4>Kütüphaneler</h4>
      </th>
</tr>


  <tr>
  <td>
    {{book.isbn}}
  </td>
  <td>
    {{book.title}}
  </td>
  <td>
    {{book.writer}}
  </td>
  <td>
    {{book.genre}}
  </td>

  <td>
    {{book.pages}}
  </td>
  <td>
    {%for unit in units%}
    {{unit}}<br>
    {%endfor%}
  </td>

</tr>

</table>
{% endblock %}